services:
  # bankshot-rs
  bankshot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - langserve
    ports:
      - "3000:3000"
    networks:
      - CTF
      - Frontend
  # langserve
  langserve:
    restart: unless-stopped
    build:
      context: ./langserve
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - ${LLM_PORT}
    hostname: ${LLM_HOST}
    networks:
      - CTF
    depends_on:
      - ollama
  ollama:
    volumes:
      - ./.ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    command: serve & sleep 3 && ollama pull mistral:instruct
    env_file:
      - .env
    expose:
      - 11434
    hostname: ${OLLAMA_HOSTNAME}
    networks:
      - CTF
      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - driver: nvidia
      #           count: 1
      #           capabilities: [gpu]
networks:
  CTF: # inner network for CTF services
    internal: true
  Frontend: # exposed to users
